version: 2.1
orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1

executors:
  node17:
    docker:
      - image: 'cypress/base:17.3.0'
workflows:
  run-cypress-tests:
    jobs:
      - cypress/install:
          yarn: true
          executor: node17
      - cypress/run:
          executor: node17
          yarn: true
          requires:
            - cypress/install
          record: true 
          parallel: true
          parallelism: 4
          group: 'TasteBin E2E tests'
          start: 'yarn dev'
  run-api-tests:
    jobs:
      - node/test:
          version: "17.6.0"
          pkg-manager: yarn
